### ISSUE TITLE
What is required to plot a new layer type?

### ISSUE THREAD

**Issue by musoke** [rmsrosa/ChainPlot.jl#10] opened 2023-05-01 23:10 UTC
I have defined a new layer which contains a [SparseMatrixCSC](https://docs.julialang.org/en/v1/stdlib/SparseArrays/#SparseArrays.SparseMatrixCSC).    I would like to plot this layer to show how if differs from Dense.

Is this possible already?  It seems not, but I may have missed something.

If not, what functions must be defined to plot such a layer?

**Comment by rmsrosa** [comment] 2023-05-01 23:24
It should work right away, as long as there is not much type restriction since it works by applying it to an array made of a special type which is a subtype of `Real`.

If it is a fixed-size layer, it helps to define `layerdimensions()` for it, as in https://github.com/rmsrosa/ChainPlots.jl/blob/main/src/utils.jl#L6, but that is not necessary.

Please, give it a go and either mention here and close the issue if it works or post here an MWE if any problem occurs. Thanks.

**Comment by musoke** [comment] 2023-05-01 23:47
Will do!

**Comment by musoke** [comment] 2023-05-02 17:37
Here's an MWE:
```
using ChainPlots
using Flux
using Optimisers
using Plots
using SparseArrays

struct SparseLayer{T,I}
    W::SparseMatrixCSC{T,I}
    b::Vector{T}
end

Flux.@functor SparseLayer
Flux.trainable(l::SparseLayer) = (W=l.W.nzval, b=l.b)
Optimisers.maywrite(::SparseArrays.SparseMatrixCSC{Float32,Int64}) = true  #TODO: is this right?

function SparseLayer((in, out)::Pair; bias=true, init=Flux.randn32)
    W = sprand(Float32, out, in, 0.5)

    b = init(out)

    return SparseLayer(W, b)
end

(m::SparseLayer)(x) = m.W * x .+ m.b

nnr = Chain(
            Dense(2 => 5),
            # Dense(5 => 4),
            SparseLayer(5 => 4),
           )

fig = plot(nnr, title="With SparseLayer default", titlefontsize=10)

savefig(fig, "layers.png")

```

It works if the `SparseLayer(5 => 4)` in `nnr` is switched with `Dense(5 => 4)` and the output is quite nice.


With the `SparseLayer` I defined, I get an error. The start of the stacktrace is
```
ERROR: LoadError: MethodError: no method matching SparseLayer(::Matrix{ChainPlots.NeuralNumbers.NeuralNumber}, ::Vector{ChainPlots.NeuralNumbers.NeuralNumber})

Closest candidates are:
  SparseLayer(!Matched::SparseMatrixCSC{T, I}, ::Vector{T}) where {T, I}
   @ Main ~/tmp/chainpoint-sparse/plot.jl:8

Stacktrace:
  [1] (::var"#3#4")(y::NamedTuple{(:W, :b), Tuple{Matrix{ChainPlots.NeuralNumbers.NeuralNumber}, Vector{ChainPlots.NeuralNumbers.NeuralNumber}}})
    @ Main ~/.julia/packages/Functors/qBIlC/src/functor.jl:23
  [2] _default_walk(f::Function, x::SparseLayer{Float32, Int64})
    @ Functors ~/.julia/packages/Functors/qBIlC/src/functor.jl:43
  [3] fmap(f::ChainPlots.NeuralNumbers.var"#1#2", x::SparseLayer{Float32, Int64}; exclude::typeof(Functors.isleaf), walk::typeof(Functors._default_walk), cache::IdDict{Any, Any}, prune::Functors.NoKeyword)
    @ Functors ~/.julia/packages/Functors/qBIlC/src/functor.jl:50
  [4] fmap
    @ ~/.julia/packages/Functors/qBIlC/src/functor.jl:48 [inlined]
  [5] #18
    @ ~/.julia/packages/Functors/qBIlC/src/functor.jl:50 [inlined]
  [6] map
    @ ./tuple.jl:274 [inlined]
  [7] _default_walk
    @ ~/.julia/packages/Functors/qBIlC/src/functor.jl:43 [inlined]
  [8] fmap(f::ChainPlots.NeuralNumbers.var"#1#2", x::Tuple{Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}, SparseLayer{Float32, Int64}}; exclude::typeof(Functors.isleaf), walk::typeof(Functors._default_walk), cache::IdDict{Any, Any}, prune::Functors.NoKeyword)
    @ Functors ~/.julia/packages/Functors/qBIlC/src/functor.jl:50
  [9] fmap
    @ ~/.julia/packages/Functors/qBIlC/src/functor.jl:48 [inlined]
 [10] (::Functors.var"#18#19"{typeof(Functors.isleaf), typeof(Functors._default_walk), IdDict{Any, Any}, Functors.NoKeyword, ChainPlots.NeuralNumbers.var"#1#2"})(x::Tuple{Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}, SparseLayer{Float32, Int64}})
    @ Functors ~/.julia/packages/Functors/qBIlC/src/functor.jl:50
 [11] map
    @ ./tuple.jl:273 [inlined]
 [12] map(::Function, ::NamedTuple{(:layers,), Tuple{Tuple{Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}, SparseLayer{Float32, Int64}}}})
    @ Base ./namedtuple.jl:219
 [13] _default_walk(f::Function, x::Chain{Tuple{Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}, SparseLayer{Float32, Int64}}})
    @ Functors ~/.julia/packages/Functors/qBIlC/src/functor.jl:43
 [14] fmap(f::ChainPlots.NeuralNumbers.var"#1#2", x::Chain{Tuple{Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}, SparseLayer{Float32, Int64}}}; exclude::typeof(Functors.isleaf), walk::typeof(Functors._default_walk), cache::IdDict{Any, Any}, prune::Functors.NoKeyword)
    @ Functors ~/.julia/packages/Functors/qBIlC/src/functor.jl:50
 [15] fmap
    @ ~/.julia/packages/Functors/qBIlC/src/functor.jl:48 [inlined]
 [16] fneutralize
    @ ~/.julia/packages/ChainPlots/Spvi6/src/NeuralNumbers.jl:133 [inlined]
 [17] neuron_connections(m::Chain{Tuple{Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}, SparseLayer{Float32, Int64}}}, input_data::Vector{Float32})
    @ ChainPlots ~/.julia/packages/ChainPlots/Spvi6/src/utils.jl:78
```

**Comment by rmsrosa** [comment] 2023-05-03 12:49
I see. You have `SparseMatrixCSC` hardcoded to the type. But can't you simply create a dense layer with a sparse matrix weigth, as in `Dense(sprand(Float32, in, out, 0.5), Flux.randn32(in))`?

**Comment by musoke** [comment] 2023-05-03 15:50
Creating the layer like that is much simpler, thanks!

The plot doesn't quite capture what I want to do with it though.  I am writing a layer in which many of the possible connections are turned off (sort of like a fixed dropout) and I want the plot to only show a lines between nodes that are connected.

Here's a script and the output:
```
using ChainPlots
using Flux
using Plots
using SparseArrays

rows = [1, 2, 3, 4, 3]
cols = [1, 2, 3, 4, 5]
vals = [1, 1, 1, 1, 1]

l = Dense(sparse(rows, cols, vals, 4, 5))

nnr = Chain(
            Dense(2 => 5),
            l,
           )

fig = plot(nnr)

savefig(fig, "layers.png")
```
![layers](https://user-images.githubusercontent.com/16665084/235964301-3db0433a-1849-444c-8afd-c7f87676d3b9.png)

I'm hoping to see only a few edges between the 2nd and 3rd layers, connecting 1->1, 2->2, 3->3, 4->4 and  5->3.
Does that make sense?

**Comment by rmsrosa** [comment] 2023-05-03 17:05
Yeah, I saw that coming. I thought that would be what you expected.

The problem is that you want the zeros from the sparse array to behave differently than zeros on regular arrays on layer weights. We would need to change the internals to make this work this way.

Another way is to not do `Flux.@functor SparseLayer`, in which case `ChainPlots` would handle this layer as a regular function and not mess with it. In this case, the connections will be showed as you wish.

If you really need to parametrize `SparseLayer`, then a quick workaround would be to have an alternate `SparseLayerAlt` without Functor parametrization, just for showing the connections. Actually, you can just use a Dense layer with a sparse weight in your application and use `SparseLayer` without parametrization just for plotting the connections.

**Comment by rmsrosa** [comment] 2023-05-03 20:04
You can even get away with simply

```julia


makesparselayer(W, b) = (sparselayer(x) = W * x + b)

nnr = Chain(
    Dense(2 => 5),
    makesparselayer(
        sprand(Float32, 2, 5, 0.3),
        rand(Float32, 2)
   )
)

plot(nnr)
```

and get

<img width="590" alt="Screen Shot 2023-05-03 at 17 03 11" src="https://user-images.githubusercontent.com/17986148/236035463-418f8457-7ca2-4e5d-9caf-37aafdec68d0.png">

**Comment by musoke** [comment] 2023-05-03 20:46
Ok, there are a couple options - I'll have to have a think about how they work

Thank you!

**Comment by musoke** [comment] 2023-05-25 20:53
For anyone else who stumbles upon this:

I ended up doing something similar to this suggestion:

> Actually, you can just use a Dense layer with a sparse weight in your application and use `SparseLayer` without parametrization just for plotting the connections.

I just wrote a function to map a `Chain` containing `Dense(w::SparseMatrix, b)` layers to the equivalent `Chain` with those layers replaced by their corresponding regular functions.  Its output acts as desired when used in ChainPlots.jl.

```
function functionise_sparse_layer(layer)
    return if typeof(layer) <: Dense && layer.weight isa AbstractSparseMatrix
        sparselayer(x) = layer(x)
    else
        layer
    end
end

function functionise_sparse_chain(chain)
    layers = map(functionise_sparse_layer, chain.layers)

    return Chain(layers...)
end
```

**Comment by rmsrosa** [comment] 2023-05-26 10:52
Great! I am glad you sorted it out. I will close the issue but feel free to open it if needed.

**Closed as completed by rmsrosa** 2023-05-26 10:52 UTC
